/*
  MIGRACION 006 - COSTOS OPERATIVOS Y COSTO REAL DE COMPRA

  Funcion que realiza:
  - Crea dbo.COSTO_OPERATIVO para registrar gastos como energia, transporte,
    alquiler, internet, empaque, mantenimiento y otros costos indirectos.
  - Agrega columnas opcionales a COMPRA_EFECTIVO y COMPRA_CREDITO para guardar
    el costo de transporte total del viaje, otros costos directos, costo adicional
    por unidad y costo real unitario usado en la compra.

  Datos que genera:
  - Los costos operativos se muestran en el modulo Costos.
  - Los costos adicionales por compra permiten calcular:
      costo_adicional_unidad = (transporte + otros_costos_directos) / unidades_del_viaje
      costo_real_unitario = costo_producto_unitario + costo_adicional_unidad

  Conexion/procedimientos:
  - Backend: server/data-access.js, funciones listOperationalCosts(),
    createOperationalCost() y registerPurchase().
*/

IF OBJECT_ID('dbo.COSTO_OPERATIVO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.COSTO_OPERATIVO (
    ID_COSTO_OPERATIVO INT IDENTITY(1,1) PRIMARY KEY,
    FECHA DATE NOT NULL,
    TIPO VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(250) NULL,
    MONTO DECIMAL(18,2) NOT NULL,
    ID_USUARIO INT NULL,
    ID_FACT INT NULL,
    NUM_FACT VARCHAR(80) NULL,
    ID_COMPRA INT NULL,
    TIPO_COMPRA VARCHAR(20) NULL,
    APLICA_A VARCHAR(40) NOT NULL CONSTRAINT DF_COSTO_OPERATIVO_APLICA_A DEFAULT ('MES'),
    REFERENCIA VARCHAR(120) NULL,
    FECHA_HORA DATETIME2 NOT NULL CONSTRAINT DF_COSTO_OPERATIVO_FECHA_HORA DEFAULT (SYSDATETIME())
  );
END;

IF COL_LENGTH('dbo.COSTO_OPERATIVO', 'ID_FACT') IS NULL
  ALTER TABLE dbo.COSTO_OPERATIVO ADD ID_FACT INT NULL;

IF COL_LENGTH('dbo.COSTO_OPERATIVO', 'NUM_FACT') IS NULL
  ALTER TABLE dbo.COSTO_OPERATIVO ADD NUM_FACT VARCHAR(80) NULL;

IF COL_LENGTH('dbo.COSTO_OPERATIVO', 'ID_COMPRA') IS NULL
  ALTER TABLE dbo.COSTO_OPERATIVO ADD ID_COMPRA INT NULL;

IF COL_LENGTH('dbo.COSTO_OPERATIVO', 'TIPO_COMPRA') IS NULL
  ALTER TABLE dbo.COSTO_OPERATIVO ADD TIPO_COMPRA VARCHAR(20) NULL;

IF COL_LENGTH('dbo.COMPRA_EFECTIVO', 'COSTO_TRANSPORTE_TOTAL') IS NULL
  ALTER TABLE dbo.COMPRA_EFECTIVO ADD COSTO_TRANSPORTE_TOTAL DECIMAL(18,2) NULL;

IF COL_LENGTH('dbo.COMPRA_EFECTIVO', 'OTROS_COSTOS_DIRECTOS') IS NULL
  ALTER TABLE dbo.COMPRA_EFECTIVO ADD OTROS_COSTOS_DIRECTOS DECIMAL(18,2) NULL;

IF COL_LENGTH('dbo.COMPRA_EFECTIVO', 'COSTO_ADICIONAL_UNIDAD') IS NULL
  ALTER TABLE dbo.COMPRA_EFECTIVO ADD COSTO_ADICIONAL_UNIDAD DECIMAL(18,4) NULL;

IF COL_LENGTH('dbo.COMPRA_EFECTIVO', 'COSTO_REAL_UNITARIO') IS NULL
  ALTER TABLE dbo.COMPRA_EFECTIVO ADD COSTO_REAL_UNITARIO DECIMAL(18,4) NULL;

IF COL_LENGTH('dbo.COMPRA_CREDITO', 'COSTO_TRANSPORTE_TOTAL') IS NULL
  ALTER TABLE dbo.COMPRA_CREDITO ADD COSTO_TRANSPORTE_TOTAL DECIMAL(18,2) NULL;

IF COL_LENGTH('dbo.COMPRA_CREDITO', 'OTROS_COSTOS_DIRECTOS') IS NULL
  ALTER TABLE dbo.COMPRA_CREDITO ADD OTROS_COSTOS_DIRECTOS DECIMAL(18,2) NULL;

IF COL_LENGTH('dbo.COMPRA_CREDITO', 'COSTO_ADICIONAL_UNIDAD') IS NULL
  ALTER TABLE dbo.COMPRA_CREDITO ADD COSTO_ADICIONAL_UNIDAD DECIMAL(18,4) NULL;

IF COL_LENGTH('dbo.COMPRA_CREDITO', 'COSTO_REAL_UNITARIO') IS NULL
  ALTER TABLE dbo.COMPRA_CREDITO ADD COSTO_REAL_UNITARIO DECIMAL(18,4) NULL;
