USE [yahweh_rohi_inventory];
GO

SET XACT_ABORT ON;
GO

IF OBJECT_ID('dbo.PRODUCTO_LOTE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCTO_LOTE (
    ID_LOTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    CODIGO_PRODUCTO VARCHAR(120) NOT NULL,
    NUM_LOTE VARCHAR(80) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NULL,
    CANTIDAD_INICIAL DECIMAL(18, 2) NOT NULL,
    CANTIDAD_DISPONIBLE DECIMAL(18, 2) NOT NULL,
    COSTO_UNITARIO DECIMAL(18, 4) NOT NULL,
    ID_COMPRA INT NULL,
    TABLA_COMPRA VARCHAR(80) NULL,
    NUM_FACT VARCHAR(80) NULL,
    ESTADO VARCHAR(20) NOT NULL CONSTRAINT DF_PRODUCTO_LOTE_ESTADO DEFAULT 'ACTIVO',
    ORIGEN VARCHAR(40) NOT NULL CONSTRAINT DF_PRODUCTO_LOTE_ORIGEN DEFAULT 'COMPRA',
    CREADO_POR VARCHAR(120) NULL,
    CREADO_EN DATETIME2 NOT NULL CONSTRAINT DF_PRODUCTO_LOTE_CREADO_EN DEFAULT SYSDATETIME(),
    ACTUALIZADO_EN DATETIME2 NULL
  );

  CREATE INDEX IX_PRODUCTO_LOTE_FEFO
    ON dbo.PRODUCTO_LOTE (ID_PRODUCTO, ESTADO, FECHA_VENCIMIENTO, FECHA_INGRESO, ID_LOTE)
    INCLUDE (CANTIDAD_DISPONIBLE);

  CREATE INDEX IX_PRODUCTO_LOTE_CODIGO
    ON dbo.PRODUCTO_LOTE (CODIGO_PRODUCTO, NUM_LOTE);
END;
GO

IF OBJECT_ID('dbo.VENTA_LOTE_DETALLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.VENTA_LOTE_DETALLE (
    ID_VENTA_LOTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_FACT INT NOT NULL,
    TABLA_VENTA VARCHAR(80) NOT NULL,
    ID_VENTA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_LOTE INT NOT NULL,
    CANTIDAD DECIMAL(18, 2) NOT NULL,
    ACCION VARCHAR(20) NOT NULL CONSTRAINT DF_VENTA_LOTE_DETALLE_ACCION DEFAULT 'VENTA',
    FECHA_HORA DATETIME2 NOT NULL CONSTRAINT DF_VENTA_LOTE_DETALLE_FECHA DEFAULT SYSDATETIME(),
    USUARIO VARCHAR(120) NULL
  );

  CREATE INDEX IX_VENTA_LOTE_DETALLE_FACTURA
    ON dbo.VENTA_LOTE_DETALLE (ID_FACT, ID_PRODUCTO, ACCION);

  CREATE INDEX IX_VENTA_LOTE_DETALLE_LOTE
    ON dbo.VENTA_LOTE_DETALLE (ID_LOTE);
END;
GO

INSERT INTO dbo.PRODUCTO_LOTE (
  ID_PRODUCTO,
  CODIGO_PRODUCTO,
  NUM_LOTE,
  FECHA_INGRESO,
  FECHA_VENCIMIENTO,
  CANTIDAD_INICIAL,
  CANTIDAD_DISPONIBLE,
  COSTO_UNITARIO,
  ID_COMPRA,
  TABLA_COMPRA,
  NUM_FACT,
  ESTADO,
  ORIGEN,
  CREADO_POR
)
SELECT
  p.id_producto,
  p.codigo,
  CONCAT('INICIAL-', p.codigo),
  CAST(GETDATE() AS DATE),
  TRY_CONVERT(DATE, i.FECHA_VENCIMIENTO),
  CAST(ISNULL(i.stock, 0) AS DECIMAL(18, 2)),
  CAST(ISNULL(i.stock, 0) AS DECIMAL(18, 2)),
  CAST(ISNULL(i.precio_costo, 0) AS DECIMAL(18, 4)),
  NULL,
  NULL,
  'MIGRACION_INVENTARIO',
  CASE WHEN ISNULL(i.stock, 0) > 0 THEN 'ACTIVO' ELSE 'AGOTADO' END,
  'MIGRACION_INVENTARIO',
  'FEFO_INICIAL'
FROM dbo.producto p
INNER JOIN dbo.inventario i
  ON i.id_inventario = p.id_producto
WHERE p.activo = 1
  AND ISNULL(i.stock, 0) > 0
  AND NOT EXISTS (
    SELECT 1
    FROM dbo.PRODUCTO_LOTE l
    WHERE l.ID_PRODUCTO = p.id_producto
      AND l.ORIGEN = 'MIGRACION_INVENTARIO'
  );
GO
