SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.COTIZACION', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.COTIZACION (
      ID_COTIZACION INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
      NUM_COTIZACION AS ('COT-' + RIGHT('000000' + CONVERT(VARCHAR(12), ID_COTIZACION), 6)) PERSISTED,
      ID_CLIENTE INT NULL,
      CLIENTE_NOMBRE NVARCHAR(250) NULL,
      ID_TP INT NOT NULL DEFAULT 1,
      SUBTOTAL DECIMAL(18, 2) NOT NULL DEFAULT 0,
      UTILIDAD_ESTIMADA DECIMAL(18, 2) NOT NULL DEFAULT 0,
      ESTADO VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
      ID_FACT INT NULL,
      USUARIO NVARCHAR(120) NULL,
      ID_USUARIO INT NULL,
      NOTA NVARCHAR(500) NULL,
      FECHA_HORA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
      ACTUALIZADO_EN DATETIME2 NULL
    );
  END;

  IF OBJECT_ID('dbo.COTIZACION_DETALLE', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.COTIZACION_DETALLE (
      ID_COTIZACION_DETALLE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
      ID_COTIZACION INT NOT NULL,
      ID_PRODUCTO INT NOT NULL,
      CODIGO_PRODUCTO VARCHAR(120) NULL,
      PRODUCTO_NOMBRE NVARCHAR(250) NULL,
      CANTIDAD DECIMAL(18, 3) NOT NULL,
      PRECIO_COSTO DECIMAL(18, 4) NOT NULL DEFAULT 0,
      PRECIO_VENTA DECIMAL(18, 4) NOT NULL DEFAULT 0,
      UTILIDAD DECIMAL(18, 2) NOT NULL DEFAULT 0,
      TOTAL_LINEA DECIMAL(18, 2) NOT NULL DEFAULT 0,
      FECHA_HORA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
      CONSTRAINT FK_COTIZACION_DETALLE_COTIZACION
        FOREIGN KEY (ID_COTIZACION) REFERENCES dbo.COTIZACION(ID_COTIZACION)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_COTIZACION_ESTADO_FECHA'
      AND object_id = OBJECT_ID('dbo.COTIZACION', 'U')
  )
  BEGIN
    CREATE INDEX IX_COTIZACION_ESTADO_FECHA
      ON dbo.COTIZACION (ESTADO, FECHA_HORA DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_COTIZACION_DETALLE_COTIZACION'
      AND object_id = OBJECT_ID('dbo.COTIZACION_DETALLE', 'U')
  )
  BEGIN
    CREATE INDEX IX_COTIZACION_DETALLE_COTIZACION
      ON dbo.COTIZACION_DETALLE (ID_COTIZACION);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;

  THROW;
END CATCH;
