IF COL_LENGTH('dbo.PAGOS_CREDITO', 'FORMA_ABONO') IS NULL
BEGIN
  ALTER TABLE dbo.PAGOS_CREDITO
  ADD FORMA_ABONO VARCHAR(30) NOT NULL
    DEFAULT ('efectivo');
END;

EXEC('
  UPDATE dbo.PAGOS_CREDITO
  SET FORMA_ABONO = ''efectivo''
  WHERE FORMA_ABONO IS NULL OR LTRIM(RTRIM(FORMA_ABONO)) = '''';
');
