IF OBJECT_ID('dbo.CODIGO_ARMADO_OFERTA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CODIGO_ARMADO_OFERTA (
    ID_OFERTA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CODIGO NVARCHAR(80) NOT NULL,
    NOMBRE NVARCHAR(180) NOT NULL,
    DESCRIPCION NVARCHAR(500) NULL,
    IMAGEN_URL NVARCHAR(500) NULL,
    PRECIO_OFERTA DECIMAL(18,2) NOT NULL,
    FECHA_INICIO DATETIME2(0) NOT NULL,
    FECHA_FIN DATETIME2(0) NOT NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_CODIGO_ARMADO_OFERTA_ACTIVO DEFAULT (1),
    CREADO_POR INT NULL,
    CREADO_EN DATETIME2(0) NOT NULL CONSTRAINT DF_CODIGO_ARMADO_OFERTA_CREADO_EN DEFAULT (SYSDATETIME()),
    ACTUALIZADO_EN DATETIME2(0) NULL
  );

  CREATE UNIQUE INDEX UX_CODIGO_ARMADO_OFERTA_CODIGO
    ON dbo.CODIGO_ARMADO_OFERTA (CODIGO);
END;

IF OBJECT_ID('dbo.CODIGO_ARMADO_OFERTA', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.CODIGO_ARMADO_OFERTA', 'IMAGEN_URL') IS NULL
BEGIN
  ALTER TABLE dbo.CODIGO_ARMADO_OFERTA
    ADD IMAGEN_URL NVARCHAR(500) NULL;
END;

IF OBJECT_ID('dbo.CODIGO_ARMADO_OFERTA_DETALLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CODIGO_ARMADO_OFERTA_DETALLE (
    ID_DETALLE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_OFERTA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD DECIMAL(18,3) NOT NULL,
    ES_REGALIA BIT NOT NULL CONSTRAINT DF_CODIGO_ARMADO_OFERTA_DETALLE_REGALIA DEFAULT (0),
    PRECIO_REFERENCIA DECIMAL(18,2) NOT NULL CONSTRAINT DF_CODIGO_ARMADO_OFERTA_DETALLE_PRECIO DEFAULT (0),
    CREADO_EN DATETIME2(0) NOT NULL CONSTRAINT DF_CODIGO_ARMADO_OFERTA_DETALLE_CREADO_EN DEFAULT (SYSDATETIME()),
    CONSTRAINT FK_CODIGO_ARMADO_OFERTA_DETALLE_OFERTA
      FOREIGN KEY (ID_OFERTA) REFERENCES dbo.CODIGO_ARMADO_OFERTA(ID_OFERTA),
    CONSTRAINT FK_CODIGO_ARMADO_OFERTA_DETALLE_PRODUCTO
      FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.producto(id_producto)
  );

  CREATE INDEX IX_CODIGO_ARMADO_OFERTA_DETALLE_OFERTA
    ON dbo.CODIGO_ARMADO_OFERTA_DETALLE (ID_OFERTA);
END;

IF OBJECT_ID('dbo.VENTA_OFERTA_DETALLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.VENTA_OFERTA_DETALLE (
    ID_VENTA_OFERTA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_FACT INT NOT NULL,
    TABLA_VENTA NVARCHAR(80) NOT NULL,
    ID_VENTA INT NULL,
    ID_OFERTA INT NOT NULL,
    CODIGO_OFERTA NVARCHAR(80) NOT NULL,
    NOMBRE_OFERTA NVARCHAR(180) NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CODIGO_PRODUCTO NVARCHAR(80) NOT NULL,
    NOMBRE_PRODUCTO NVARCHAR(180) NOT NULL,
    CANTIDAD DECIMAL(18,3) NOT NULL,
    ES_REGALIA BIT NOT NULL,
    PRECIO_UNITARIO DECIMAL(18,2) NOT NULL,
    PRECIO_OFERTA DECIMAL(18,2) NOT NULL,
    FECHA_HORA DATETIME2(0) NOT NULL CONSTRAINT DF_VENTA_OFERTA_DETALLE_FECHA DEFAULT (SYSDATETIME()),
    ID_USUARIO INT NULL
  );

  CREATE INDEX IX_VENTA_OFERTA_DETALLE_FACTURA
    ON dbo.VENTA_OFERTA_DETALLE (ID_FACT, ID_OFERTA);
END;
