/*
  MIGRACION: multiples codigos de barra por producto
  - Conserva dbo.producto.codigo.
  - Crea dbo.PRODUCTO_CODIGO_BARRA como tabla hija.
  - Migra cada producto.codigo existente como codigo principal activo.
*/

IF OBJECT_ID('dbo.PRODUCTO_CODIGO_BARRA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCTO_CODIGO_BARRA (
    ID_CODIGO_BARRA int IDENTITY(1,1) NOT NULL,
    ID_PRODUCTO int NOT NULL,
    CODIGO_BARRA nvarchar(120) NOT NULL,
    ES_PRINCIPAL bit NOT NULL CONSTRAINT DF_PRODUCTO_CODIGO_BARRA_PRINCIPAL DEFAULT (0),
    ACTIVO bit NOT NULL CONSTRAINT DF_PRODUCTO_CODIGO_BARRA_ACTIVO DEFAULT (1),
    CREADO_POR nvarchar(100) NULL,
    CREADO_EN datetime2(0) NOT NULL CONSTRAINT DF_PRODUCTO_CODIGO_BARRA_CREADO_EN DEFAULT (SYSDATETIME()),
    ACTUALIZADO_POR nvarchar(100) NULL,
    ACTUALIZADO_EN datetime2(0) NULL,
    CONSTRAINT PK_PRODUCTO_CODIGO_BARRA PRIMARY KEY CLUSTERED (ID_CODIGO_BARRA),
    CONSTRAINT FK_PRODUCTO_CODIGO_BARRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
      REFERENCES dbo.producto (id_producto)
  );
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'UX_PRODUCTO_CODIGO_BARRA_CODIGO'
    AND object_id = OBJECT_ID('dbo.PRODUCTO_CODIGO_BARRA')
)
BEGIN
  CREATE UNIQUE INDEX UX_PRODUCTO_CODIGO_BARRA_CODIGO
    ON dbo.PRODUCTO_CODIGO_BARRA (CODIGO_BARRA);
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'UX_PRODUCTO_CODIGO_BARRA_PRINCIPAL_ACTIVO'
    AND object_id = OBJECT_ID('dbo.PRODUCTO_CODIGO_BARRA')
)
BEGIN
  CREATE UNIQUE INDEX UX_PRODUCTO_CODIGO_BARRA_PRINCIPAL_ACTIVO
    ON dbo.PRODUCTO_CODIGO_BARRA (ID_PRODUCTO)
    WHERE ES_PRINCIPAL = 1 AND ACTIVO = 1;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_PRODUCTO_CODIGO_BARRA_PRODUCTO'
    AND object_id = OBJECT_ID('dbo.PRODUCTO_CODIGO_BARRA')
)
BEGIN
  CREATE INDEX IX_PRODUCTO_CODIGO_BARRA_PRODUCTO
    ON dbo.PRODUCTO_CODIGO_BARRA (ID_PRODUCTO, ACTIVO, ES_PRINCIPAL);
END;

;WITH codigos_existentes AS (
  SELECT
    p.id_producto,
    LTRIM(RTRIM(CONVERT(nvarchar(120), p.codigo))) AS codigo_barra,
    ROW_NUMBER() OVER (
      PARTITION BY LTRIM(RTRIM(CONVERT(nvarchar(120), p.codigo)))
      ORDER BY ISNULL(p.activo, 0) DESC, p.id_producto ASC
    ) AS rn
  FROM dbo.producto p
  WHERE NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(120), p.codigo))), '') IS NOT NULL
)
INSERT INTO dbo.PRODUCTO_CODIGO_BARRA (
  ID_PRODUCTO,
  CODIGO_BARRA,
  ES_PRINCIPAL,
  ACTIVO,
  CREADO_POR,
  CREADO_EN
)
SELECT
  ce.id_producto,
  ce.codigo_barra,
  1,
  1,
  N'Migracion Codex',
  SYSDATETIME()
FROM codigos_existentes ce
WHERE ce.rn = 1
  AND NOT EXISTS (
    SELECT 1
    FROM dbo.PRODUCTO_CODIGO_BARRA pcb
    WHERE pcb.CODIGO_BARRA = ce.codigo_barra
  );
